### ISSUE TITLE
Cube-drone over HTTPS has stopped working

### ISSUE THREAD

**Issue by thijzert** [classam/threepanel#3]
Whenever I navigate to https://www.cube-drone.com/, I see some sort of overview panel rather than the site I was expecting.
Cube drone over HTTP works fine though.

(This was probably introduced in commit f36d52fcdad36c54dd9786efb21376abb7373ec6).

**Comment by cube-drone** [comment]
oho, it's the www. that's causing it, not the http

**Comment by cube-drone** [comment]
I think I've fixed it in the build that I just deployed.

**Comment by thijzert** [comment]
Yup, that seems to have worked. Thanks!
